backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Stories'
    label_singular: 'Story'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor: { preview: false }
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Post',
          name: 'featured',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
  - name: 'events'
    label: 'Events'
    label_singular: 'Event'
    folder: 'src/pages/events'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor: { preview: false }
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'event',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Event',
          name: 'featured',
          widget: 'boolean',
          required: false,
        }
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: image,
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
  - name: 'testimonials'
    label: 'Testimonials'
    label_singular: 'Testimonial'
    folder: 'src/pages/testimonials'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor: { preview: false }
    identifier_field: 'quote'
    fields:
      - label: 'Template Key'
        name: 'templateKey'
        widget: 'hidden'
        default: 'testimonial'
      - { label: 'Quote', name: 'quote', widget: 'text' }
      - label: 'Author'
        name: 'author'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string', required: false }
          - {
              label: 'Avatar',
              name: 'avatar',
              widget: 'image',
              required: false,
            }
  - name: 'people'
    label: 'People'
    label_singular: 'Person'
    folder: 'src/pages/people'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor: { preview: false }
    identifier_field: 'name'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'people',
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Avatar', name: 'avatar', widget: image, required: false }
      - label: 'Organization'
        name: 'org'
        widget: 'select'
        default: 'alumni'
        multiple: true
        options:
          - { label: 'Alumni Association', value: 'alumni' }
          - { label: 'Scholarship Foundation', value: 'scholarship' }
      - {
          label: 'Sort Order',
          name: 'pos',
          widget: 'number',
          value_type: 'int',
          min: 1,
          step: 1,
        }
      - {
          label: 'Additional Committee Member',
          name: 'additional',
          widget: 'boolean',
          default: false,
        }
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    editor: { preview: false }
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: 'Profile Image', name: profileImage, widget: image }
          - {
              label: Mission,
              name: mission,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                ],
            }
          - {
              label: Profile,
              name: profile,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                ],
            }
          - {
              label: Camp,
              name: camp,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                ],
            }
          - {
              label: Give,
              name: give,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/donate/index.md'
        label: 'Donate'
        name: 'donate'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'donate',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
